global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'gpu-monitor'
    static_configs:
      # - targets: ['localhost:8081']

      # docker bridge IP
      - targets: ['172.17.0.1:8081']